app_name: OpenMars Ultra
current_workspace: 新闻
models: []
theme: dark
version: 2.0.0
workspaces:
- description: 默认工作区
  is_active: false
  name: default
  path: /Users/mars/cyber-printer-pro/workspaces/default
- description: ''
  is_active: true
  name: 新闻
  path: /Users/mars/cyber-printer-pro/workspaces/新闻
